% This script is a tool to generate synthetic images simulating brain MRIs.

% First, it takes segmentation maps and is able to fuse them with more
% precise segmentation of the hippocampus (generally at higher resolution).

% Then it separately computes basic statistics of each different region in
% the brain. This is done by studying the intensity distribution in an
% example image (at the resolution of the fused labels).

% Finally, synthetic images are generated by taking fused segmentation maps
% and sampling intensities from the previously derived distributions. The
% images are always generated at the resolution of the fused labels, but
% are then downsampled to a specified target resolution.

% All files are writen in nii format (no matter input formats).

tic

clear
addpath /usr/local/freesurfer/matlab
addpath /home/benjamin/matlab/toolbox

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% parameters %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% merge labels between labels and hippocampal subfields
mergeHippoLabels = 1;
% If mergeHippoLabels = 1, specify the paths of hippocampal subfields' 
% labels. Make sure they are listed in same order as pathDirLabels.
pathDirHippoLabels = '/home/benjamin/data/CobraLab/hippocampus_labels/*labels.nii.gz';
% set how many times you want to smooth the hippocampus labels (integer)
subfieldsSmoothing = 1;

% folder containing labels to generate images from. If mergeHippoLabels = 0
% then the images will direclty be generated from these.
pathDirLabels = '/home/benjamin/data/CobraLab/original_labels/*.mgz';

% compute stats matrix from a specified image.
computeStatsMatrix = 1;
% if computeStatsMatrix=0 path where resulting stats matrix will be stored,
% if computeStatsMatrix=1 path of stats matrix to load
pathStatsMatrix = '~/matlab/brain_mri_model/ClassesStats_t1_smoothed_twice.mat';
% if computeStatsMatrix=1, image to compute stats from. Should correspond 
% to the first map in pathDirLabels (at hippocampal labels' resolution).
pathImage = '/home/benjamin/subjects/brain1_t1_to_t2.0.6/mri/norm.0.3.mgz';

% folder that will contain created images
pathNewImagesFolder = '/home/benjamin/data/CobraLab/synthetic_brains_t1/';

% define regions that we want to study and group them by class
ClassNames = ["Cerebral GM","Cerebral WM","Cerebellum GM","Cerebellum WM","Brainstem","Ventral PC","Thalamus","Caudate","Accumbens","Putamen","Pallidum","Ventricules","Choroid Plexus","Hippocampus","Amygdala","CSF","Optic Chiasm","Vessel"];
ClassIndices = '  1            2                 3            4              5            6           7          8           9         10         11         12              13              14          15      16         17          18';
labelsList = [  2,3, 4, 5,7,8,10,11,12,13,14,15,16,17,18,24,26,28,30,31,41,42,43,44,46,47,49,50,51,52,53,54,58,60,62,63,85,251,252,253,254,255,20001,20002,20004,20005,20006,20101,20102,20104,20105,20106];
labelClasses = [2,1,12,12,4,3, 7, 8,10,11,12,12, 5,14,15,16, 9, 6,18,13, 2, 1,12,12, 4, 3, 7, 8,10,11,14,15, 9, 6,18,13,17,  2,  2,  2,  2,  2,   14,   14,   14,   14,    2,   14,   14,   14,   14,    2];
listClassesToGenerate = 1:length(ClassNames); % all classes

% select type of gaussian 'mean' or 'median'
gaussianType = 'median';

% target resolution of generated images
targetRes=[0.6 0.6 0.6];
% image to use as template for downsampling
pathImageResliceLike = '/home/benjamin/subjects/brain2_t1_to_t2.0.6/mri/norm.mgz';


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% procedure %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~exist(pathNewImagesFolder, 'dir'), mkdir(pathNewImagesFolder), end

structPathsLabels = dir(pathDirLabels);
structPathsHippoLabels = dir(pathDirHippoLabels);

for i=1:length(structPathsLabels)
    
    disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
    disp(['processing ', structPathsLabels(i).name])
    
    pathLabels = fullfile(structPathsLabels(i).folder,structPathsLabels(i).name);
    pathHippoLabels = fullfile(structPathsHippoLabels(i).folder,structPathsHippoLabels(i).name);

    if mergeHippoLabels == 1
        % merge general and hippocampal labels for generative image
        disp(['%%%%%%%%%%%%%%',' merge general and hippocampal labels ', '%%%%%%%%%%%%%%%']);
        mergedLabelsMRI = mergeSubfieldLabels(pathLabels, pathHippoLabels, subfieldsSmoothing);
        mergedLabels = mergedLabelsMRI.vol;
    else
        disp(['%%%%%%%%%%%%%%%%%%%%%',' loading merged labels ', '%%%%%%%%%%%%%%%%%%%%%%%']);
        mergedLabelsMRI = MRIread(pathLabels);
        mergedLabels = mergedLabelsMRI.vol;
    end

    if i == 1
        if computeStatsMatrix == 1 
            % calculate intensity stats for all the specified regions
            disp(['%%%%%',' calculate intensity stats for all the specified regions ', '%%%%%']);
            classesStats = computeIntensityStats(pathImage, mergedLabels, labelsList, labelClasses, ClassNames, pathStatsMatrix );
        else
            disp(['%%%%%%%%%%%%%%%%%%%%%%%%%%',' loading stats ', '%%%%%%%%%%%%%%%%%%%%%%%%%%']);
            load(pathStatsMatrix,'classesStats')
        end
    end

    % create new images
    disp(['%%%%%%%%%%%%%%%%%%%%%%%%%',' create new image ', '%%%%%%%%%%%%%%%%%%%%%%%%']);
    new_image = createNewImage(mergedLabelsMRI, classesStats, listClassesToGenerate, labelsList, labelClasses, gaussianType, targetRes,...
        pathNewImagesFolder, pathStatsMatrix, pathLabels, pathImageResliceLike, downsampleWithMatlab, subfieldsSmoothing);

end

toc